### ISSUE TITLE
There are no diversity metrics in eval_diversity.py

### ISSUE THREAD

**Issue by RyanLiut** [visinf/cos-cvae#1]
Hi,

Thank you for your source code!

I wonder what the role of eval_diversity.py is, since there are no diversity metrics, like novel words, new sentences in the file. So what is the difference between eval.py and eval_diversity.py?

Thank you
Ryan.

**Comment by s-mahajan** [comment]
Hi Ryan, 
eval_diversity.py creates a numpy file for consensus reranking. 
See point 3 under pretrained models and evaluation.

Thanks, 
Shweta

**Comment by RyanLiut** [comment]
Many thanks. I got it!
